version: '3.8'

services:
  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_LANGGRAPH_API_URL=http://backend:2024
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  # LangGraph Backend
  backend:
    build:
      context: .
      dockerfile: apps/agents/Dockerfile
    ports:
      - "2024:2024"
    environment:
      - NODE_ENV=production
      - PORT=2024
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - MONGODB_URI=${MONGODB_URI}
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2024/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  app-data: