import { NextRequest, NextResponse } from 'next/server';

// Get LangGraph API URL from environment variable
const LANGGRAPH_API_URL = process.env.LANGGRAPH_API_URL || (
  process.env.NODE_ENV === 'production' ? 'http://127.0.0.1:2025' : 'http://localhost:2025'
);

interface LeanCanvasRequest {
  businessName: string;
  canvasData: Record<string, string>;
  context?: {
    timestamp?: string;
    requestType?: 'suggestion' | 'validation' | 'improvement';
  };
}

interface LeanCanvasSuggestion {
  sectionId: string;
  currentValue: string;
  suggestion: string;
  reasoning: string;
  priority: 'high' | 'medium' | 'low';
  type: 'empty' | 'insufficient' | 'improvement';
}

interface LangGraphResponse {
  success: boolean;
  suggestions: LeanCanvasSuggestion[];
  metadata?: {
    reasoning?: string;
    processingTime?: number;
    model?: string;
  };
  errors?: string[];
}

export async function POST(request: NextRequest) {
  try {
    const body: LeanCanvasRequest = await request.json();
    
    console.log('API: Received lean canvas request:', JSON.stringify(body, null, 2));

    // Call the actual LangGraph lean canvas agent
    console.log('LLM: Calling lean canvas agent for business:', body.businessName);
    
    const langGraphResponse = await fetch(`${LANGGRAPH_API_URL}/threads`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        assistant_id: '68c158ef-ac32-481d-bf97-7023e7044c70', // lean_canvas_agent ID
        input: {
          businessName: body.businessName,
          canvasData: body.canvasData,
          context: body.context
        }
      })
    });

    if (!langGraphResponse.ok) {
      throw new Error(`LangGraph API call failed: ${langGraphResponse.status} ${langGraphResponse.statusText}`);
    }

    const threadResult = await langGraphResponse.json();
    console.log('LangGraph thread created:', threadResult.thread_id);

    // Now invoke the thread to get the response
    const invokeResponse = await fetch(`${LANGGRAPH_API_URL}/threads/${threadResult.thread_id}/runs`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        assistant_id: '68c158ef-ac32-481d-bf97-7023e7044c70',
        input: {
          businessName: body.businessName,
          canvasData: body.canvasData,
          context: body.context
        }
      })
    });

    if (!invokeResponse.ok) {
      throw new Error(`LangGraph invoke failed: ${invokeResponse.status} ${invokeResponse.statusText}`);
    }

    const runResult = await invokeResponse.json();
    console.log('LangGraph run result:', JSON.stringify(runResult, null, 2));

    // Wait for the run to complete and get the final result
    const runId = runResult.run_id;
    let finalResult = runResult;
    
    // Poll for completion (max 30 seconds)
    const maxAttempts = 60; // 30 seconds with 500ms intervals
    let attempts = 0;
    
    while (finalResult.status === 'pending' && attempts < maxAttempts) {
      await new Promise(resolve => setTimeout(resolve, 500));
      
      const statusResponse = await fetch(`${LANGGRAPH_API_URL}/threads/${threadResult.thread_id}/runs/${runId}`, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        }
      });
      
      if (statusResponse.ok) {
        finalResult = await statusResponse.json();
        console.log(`Run status attempt ${attempts + 1}:`, finalResult.status);
      }
      
      attempts++;
    }
    
    console.log('Final LangGraph result:', JSON.stringify(finalResult, null, 2));

    // Get the final state values from the completed run
    const valuesResponse = await fetch(`${LANGGRAPH_API_URL}/threads/${threadResult.thread_id}/state`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      }
    });
    
    let graphOutput = {};
    
    if (valuesResponse.ok) {
      const stateData = await valuesResponse.json();
      console.log('Thread state data:', JSON.stringify(stateData, null, 2));
      
      // Extract the output from the state
      if (stateData.values && stateData.values.output) {
        graphOutput = stateData.values.output;
        console.log('Found output from thread state:', graphOutput);
      } else if (stateData.values && stateData.values.suggestions) {
        // Fallback: use suggestions directly
        graphOutput = {
          suggestions: stateData.values.suggestions,
          success: true,
          metadata: {
            reasoning: stateData.values.reasoning || 'Generated by LangGraph lean canvas agent',
            model: 'gpt-4o'
          }
        };
        console.log('Using suggestions fallback from thread state:', graphOutput);
      } else {
        console.log('No output or suggestions found in thread state. Available keys:', Object.keys(stateData.values || {}));
        // Set a default response
        graphOutput = {
          suggestions: [],
          success: true,
          metadata: {
            reasoning: 'No suggestions generated - possibly incomplete agent execution',
            model: 'gpt-4o'
          }
        };
      }
    } else {
      console.error('Failed to get thread state:', valuesResponse.status, valuesResponse.statusText);
      // Fallback when thread state retrieval fails
      graphOutput = {
        suggestions: [],
        success: true,
        metadata: {
          reasoning: 'Thread state retrieval failed - using empty response',
          model: 'gpt-4o',
          error: `State retrieval failed: ${valuesResponse.status} ${valuesResponse.statusText}`
        }
      };
    }

    // Extract the suggestions from the LangGraph response
    const output = graphOutput as any;
    
    const response: LangGraphResponse = {
      success: true,
      suggestions: output?.suggestions || [],
      metadata: output?.metadata || {
        reasoning: 'Generated by LangGraph lean canvas agent',
        model: 'gpt-4o'
      }
    };

    console.log('API: Sending response:', JSON.stringify(response, null, 2));
    
    return NextResponse.json(response);

  } catch (error) {
    console.error('Lean canvas API route error:', error);
    
    return NextResponse.json({
      success: false,
      suggestions: [],
      metadata: {
        reasoning: 'Error occurred during processing',
        model: 'gpt-4o',
        error: error instanceof Error ? error.message : 'Unknown error'
      }
    }, { status: 500 });
  }
}

